'use strict';

/**
 * Tests for A1 AGENTS.md alias (wf-a346c915).
 *
 * Verifies the write path for CLAUDE.md + AGENTS.md siblings:
 * - writeGeneratedRulesFile() respects manual-edit guard (no marker = skip)
 * - writeGeneratedRulesFile() writes when marker present
 * - generateRulesFile() emits both files when config flag default/true
 * - generateRulesFile() emits only CLAUDE.md when flag is false
 *
 * Development-only — not distributed to end users.
 * Run: NODE_ENV=test node --test tests/agents-md-alias.test.js
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const BaseBridge = require('../.workflow/bridges/base-bridge');
const { writeGeneratedRulesFile } = BaseBridge;

let tmpDir;

before(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'wogi-agents-md-'));
});

after(() => {
  try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch (_err) { /* ignore */ }
});

function scratchPath(name) {
  return path.join(tmpDir, `${Date.now()}-${Math.random().toString(36).slice(2)}-${name}`);
}

describe('writeGeneratedRulesFile — shared write guard', () => {
  it('writes file when target does not exist', () => {
    const p = scratchPath('CLAUDE.md');
    const ok = writeGeneratedRulesFile(p, '# Hi\n\nGenerated by CLI Bridge\n');
    assert.equal(ok, true);
    assert.equal(fs.readFileSync(p, 'utf-8'), '# Hi\n\nGenerated by CLI Bridge\n');
  });

  it('skips overwrite when existing file lacks generation marker (no force)', () => {
    const p = scratchPath('AGENTS.md');
    fs.writeFileSync(p, '# Hand-written project instructions — DO NOT OVERWRITE\n', 'utf-8');
    const ok = writeGeneratedRulesFile(p, '# Generated\n\nGenerated by CLI Bridge\n');
    assert.equal(ok, false, 'manually-edited file must be preserved');
    assert.match(fs.readFileSync(p, 'utf-8'), /Hand-written/);
  });

  it('overwrites manually-edited file with force=true', () => {
    const p = scratchPath('AGENTS.md');
    fs.writeFileSync(p, '# Hand-written\n', 'utf-8');
    const ok = writeGeneratedRulesFile(p, '# New\n\nGenerated by CLI Bridge\n', { force: true });
    assert.equal(ok, true);
    assert.match(fs.readFileSync(p, 'utf-8'), /Generated by CLI Bridge/);
  });

  it('overwrites existing generated file when content changed', () => {
    const p = scratchPath('CLAUDE.md');
    fs.writeFileSync(p, '# Old\n\nGenerated by CLI Bridge\n', 'utf-8');
    const ok = writeGeneratedRulesFile(p, '# New\n\nGenerated by CLI Bridge\n');
    assert.equal(ok, true);
    assert.match(fs.readFileSync(p, 'utf-8'), /^# New/);
  });

  it('reports up-to-date without rewriting when content matches', () => {
    const p = scratchPath('CLAUDE.md');
    const content = '# Same\n\nGenerated by CLI Bridge\n';
    fs.writeFileSync(p, content, 'utf-8');
    const mtimeBefore = fs.statSync(p).mtimeMs;
    // Small sleep to ensure mtime resolution would pick up a rewrite
    const deadline = Date.now() + 15;
    while (Date.now() < deadline) { /* busy-wait */ }
    const ok = writeGeneratedRulesFile(p, content);
    const mtimeAfter = fs.statSync(p).mtimeMs;
    assert.equal(ok, true);
    assert.equal(mtimeAfter, mtimeBefore, 'unchanged content should not trigger a write');
  });
});

// ----------------------------------------------------------------------
// Integration: generateRulesFile() writes both CLAUDE.md and AGENTS.md
// ----------------------------------------------------------------------

class TestBridge extends BaseBridge {
  constructor(opts) {
    super('test-cli', opts);
    this._rulesFileName = 'CLAUDE.md';
    this._config = opts.config;
    this._content = opts.content;
  }
  getCliFolder() { return '.test'; }
  getRulesFileName() { return this._rulesFileName; }
  readConfig() { return this._config; }
  generateRulesContent() { return this._content; }
  log() { /* silent */ }
}

describe('generateRulesFile — dual-write of CLAUDE.md + AGENTS.md', () => {
  it('writes both when cli.generateAgentsMd is unset (default on)', () => {
    const projectDir = fs.mkdtempSync(path.join(tmpDir, 'proj-default-'));
    const bridge = new TestBridge({
      projectDir,
      config: { cli: { type: 'test-cli' } },  // flag absent
      content: '# Rules\n\nGenerated by CLI Bridge\n',
    });
    bridge.generateRulesFile();
    assert.equal(fs.existsSync(path.join(projectDir, 'CLAUDE.md')), true);
    assert.equal(fs.existsSync(path.join(projectDir, 'AGENTS.md')), true);
    assert.equal(
      fs.readFileSync(path.join(projectDir, 'CLAUDE.md'), 'utf-8'),
      fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8'),
      'CLAUDE.md and AGENTS.md must be byte-identical'
    );
  });

  it('writes both when cli.generateAgentsMd === true', () => {
    const projectDir = fs.mkdtempSync(path.join(tmpDir, 'proj-explicit-on-'));
    const bridge = new TestBridge({
      projectDir,
      config: { cli: { type: 'test-cli', generateAgentsMd: true } },
      content: '# Rules\n\nGenerated by CLI Bridge\n',
    });
    bridge.generateRulesFile();
    assert.equal(fs.existsSync(path.join(projectDir, 'AGENTS.md')), true);
  });

  it('writes ONLY CLAUDE.md when cli.generateAgentsMd === false', () => {
    const projectDir = fs.mkdtempSync(path.join(tmpDir, 'proj-off-'));
    const bridge = new TestBridge({
      projectDir,
      config: { cli: { type: 'test-cli', generateAgentsMd: false } },
      content: '# Rules\n\nGenerated by CLI Bridge\n',
    });
    bridge.generateRulesFile();
    assert.equal(fs.existsSync(path.join(projectDir, 'CLAUDE.md')), true);
    assert.equal(fs.existsSync(path.join(projectDir, 'AGENTS.md')), false);
  });

  it('preserves a manually-maintained AGENTS.md (no marker) even while regenerating CLAUDE.md', () => {
    const projectDir = fs.mkdtempSync(path.join(tmpDir, 'proj-preserve-agents-'));
    const userAgents = '# My hand-written AGENTS.md\n';
    fs.writeFileSync(path.join(projectDir, 'AGENTS.md'), userAgents, 'utf-8');

    const bridge = new TestBridge({
      projectDir,
      config: { cli: { type: 'test-cli' } },
      content: '# Generated\n\nGenerated by CLI Bridge\n',
    });
    bridge.generateRulesFile();

    assert.equal(fs.existsSync(path.join(projectDir, 'CLAUDE.md')), true);
    assert.equal(
      fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8'),
      userAgents,
      'user-authored AGENTS.md must not be overwritten without --force'
    );
  });

  it('overwrites both files when options.force is true', () => {
    const projectDir = fs.mkdtempSync(path.join(tmpDir, 'proj-force-'));
    fs.writeFileSync(path.join(projectDir, 'AGENTS.md'), '# Hand-written\n', 'utf-8');
    fs.writeFileSync(path.join(projectDir, 'CLAUDE.md'), '# Hand-written\n', 'utf-8');

    const bridge = new TestBridge({
      projectDir,
      config: { cli: { type: 'test-cli' } },
      content: '# Generated\n\nGenerated by CLI Bridge\n',
    });
    bridge.generateRulesFile({ force: true });

    assert.match(fs.readFileSync(path.join(projectDir, 'CLAUDE.md'), 'utf-8'), /Generated by CLI Bridge/);
    assert.match(fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8'), /Generated by CLI Bridge/);
  });
});
