/**
 * Base Bridge Class
 *
 * Abstract base class for CLI bridges. Each supported CLI (Claude Code, Gemini CLI, etc.)
 * extends this class to generate its specific file structure from the universal .workflow/ config.
 *
 * Architecture:
 *
 * .workflow/                    ← Universal source of truth
 * ├── config.json              ← Contains cli.type setting
 * ├── models/                  ← Model registry (CLI-agnostic)
 * ├── skills/                  ← Skills (CLI-agnostic)
 * └── templates/               ← Templates for generating CLI files
 *          │
 *          ▼ (bridge generates CLI-specific files)
 * .claude/ or .gemini/ etc.   ← Generated by bridge
 */

const fs = require('fs');
const path = require('path');

class BaseBridge {
  /**
   * @param {string} cliType - The CLI type identifier (e.g., 'claude-code', 'gemini-cli')
   * @param {Object} options - Configuration options
   * @param {string} options.workflowDir - Path to .workflow directory
   * @param {string} options.projectDir - Path to project root
   */
  constructor(cliType, options = {}) {
    this.cliType = cliType;
    this.workflowDir = options.workflowDir || '.workflow';
    this.projectDir = options.projectDir || process.cwd();
    this.verbose = options.verbose || false;

    // These must be overridden by subclasses
    this.cliFolder = null;       // e.g., '.claude', '.gemini'
    this.rulesFile = null;       // e.g., 'CLAUDE.md', 'GEMINI.md'
    this.skillsPath = null;      // e.g., '.claude/skills'
    this.rulesPath = null;       // e.g., '.claude/rules'
  }

  /**
   * Get the CLI-specific folder name
   * @abstract
   * @returns {string}
   */
  getCliFolder() {
    throw new Error('Subclass must implement getCliFolder()');
  }

  /**
   * Get the rules file name (e.g., CLAUDE.md)
   * @abstract
   * @returns {string}
   */
  getRulesFileName() {
    throw new Error('Subclass must implement getRulesFileName()');
  }

  /**
   * Get the path where skills should be synced
   * @abstract
   * @returns {string}
   */
  getSkillsPath() {
    throw new Error('Subclass must implement getSkillsPath()');
  }

  /**
   * Get the path where rules should be synced
   * @abstract
   * @returns {string}
   */
  getRulesPath() {
    throw new Error('Subclass must implement getRulesPath()');
  }

  /**
   * Generate the main rules/instructions file content
   * @abstract
   * @param {Object} config - The workflow config
   * @returns {string}
   */
  generateRulesContent(config) {
    throw new Error('Subclass must implement generateRulesContent()');
  }

  /**
   * Perform any CLI-specific setup
   * @abstract
   * @param {Object} config - The workflow config
   */
  async setupCliSpecific(config) {
    // Default: no-op. Override in subclasses if needed.
  }

  // ==================== Common Methods ====================

  /**
   * Safe JSON parse that checks for prototype pollution
   * @param {string} content - JSON string to parse
   * @returns {Object|null} Parsed object or null if invalid
   */
  safeJsonParse(content) {
    // Check for prototype pollution attempts
    if (content.includes('__proto__') || content.includes('constructor"')) {
      this.log('Warning: Potential prototype pollution detected in JSON');
      return null;
    }

    try {
      const parsed = JSON.parse(content);
      if (parsed === null || typeof parsed !== 'object') {
        return null;
      }
      return parsed;
    } catch {
      return null;
    }
  }

  /**
   * Read the workflow config
   * @returns {Object}
   */
  readConfig() {
    const configPath = path.join(this.projectDir, this.workflowDir, 'config.json');
    if (!fs.existsSync(configPath)) {
      throw new Error(`Config not found: ${configPath}`);
    }

    const content = fs.readFileSync(configPath, 'utf-8');
    const config = this.safeJsonParse(content);
    if (!config) {
      throw new Error(`Invalid config format: ${configPath}`);
    }
    return config;
  }

  /**
   * Ensure the CLI folder exists
   */
  ensureCliFolder() {
    const cliFolder = path.join(this.projectDir, this.getCliFolder());
    if (!fs.existsSync(cliFolder)) {
      fs.mkdirSync(cliFolder, { recursive: true });
      this.log(`Created ${this.getCliFolder()}/`);
    }
  }

  /**
   * Sync skills from .workflow/skills/ to CLI-specific location
   */
  syncSkills() {
    const sourceSkillsDir = path.join(this.projectDir, this.workflowDir, 'skills');
    const targetSkillsDir = path.join(this.projectDir, this.getSkillsPath());

    if (!fs.existsSync(sourceSkillsDir)) {
      this.log('No skills to sync (no .workflow/skills/ directory)');
      return;
    }

    // Ensure target directory exists
    if (!fs.existsSync(targetSkillsDir)) {
      fs.mkdirSync(targetSkillsDir, { recursive: true });
    }

    // Copy skills
    const skills = fs.readdirSync(sourceSkillsDir).filter(item => {
      const itemPath = path.join(sourceSkillsDir, item);
      return fs.statSync(itemPath).isDirectory();
    });

    for (const skill of skills) {
      const sourcePath = path.join(sourceSkillsDir, skill);
      const targetPath = path.join(targetSkillsDir, skill);

      this.copyDirRecursive(sourcePath, targetPath);
      this.log(`Synced skill: ${skill}`);
    }

    // Also copy skills-index.json if it exists
    const indexPath = path.join(sourceSkillsDir, 'skills-index.json');
    if (fs.existsSync(indexPath)) {
      fs.copyFileSync(indexPath, path.join(targetSkillsDir, 'skills-index.json'));
      this.log('Synced skills-index.json');
    }
  }

  /**
   * Sync rules from .workflow/state/decisions.md to CLI-specific rules folder
   */
  syncRules() {
    const rulesDir = path.join(this.projectDir, this.getRulesPath());

    // Ensure rules directory exists
    if (!fs.existsSync(rulesDir)) {
      fs.mkdirSync(rulesDir, { recursive: true });
    }

    // Copy any existing rules from .workflow/rules/ if present
    const sourceRulesDir = path.join(this.projectDir, this.workflowDir, 'rules');
    if (fs.existsSync(sourceRulesDir)) {
      const rules = fs.readdirSync(sourceRulesDir).filter(f => f.endsWith('.md'));
      for (const rule of rules) {
        fs.copyFileSync(
          path.join(sourceRulesDir, rule),
          path.join(rulesDir, rule)
        );
        this.log(`Synced rule: ${rule}`);
      }
    }
  }

  /**
   * Sync knowledge files from .workflow/state/ to CLI-specific docs folder
   * Also updates the knowledge-sync.json state
   */
  syncKnowledgeFiles() {
    const stateDir = path.join(this.projectDir, this.workflowDir, 'state');
    const cliDocsDir = path.join(this.projectDir, this.getCliFolder(), 'docs');

    // Knowledge files to sync
    const knowledgeFiles = ['stack.md', 'architecture.md', 'testing.md'];

    // Ensure CLI docs directory exists
    if (!fs.existsSync(cliDocsDir)) {
      fs.mkdirSync(cliDocsDir, { recursive: true });
    }

    let syncedCount = 0;
    for (const file of knowledgeFiles) {
      const sourcePath = path.join(stateDir, file);
      const targetPath = path.join(cliDocsDir, file);

      if (fs.existsSync(sourcePath)) {
        fs.copyFileSync(sourcePath, targetPath);
        this.log(`Synced knowledge file: ${file}`);
        syncedCount++;
      }
    }

    // Update knowledge-sync.json after bridge sync
    if (syncedCount > 0) {
      try {
        const knowledgeSync = require('../../scripts/flow-knowledge-sync');
        knowledgeSync.markAsSynced();
        this.log('Updated knowledge-sync.json');
      } catch (err) {
        // flow-knowledge-sync not available
        this.log(`Could not update knowledge-sync state: ${err.message}`);
      }
    }

    return syncedCount;
  }

  /**
   * Generate and write the main rules file (e.g., CLAUDE.md)
   */
  generateRulesFile() {
    const config = this.readConfig();
    const content = this.generateRulesContent(config);
    const rulesFilePath = path.join(this.projectDir, this.getRulesFileName());

    fs.writeFileSync(rulesFilePath, content, 'utf-8');
    this.log(`Generated ${this.getRulesFileName()}`);
  }

  /**
   * Run full sync: skills, rules, and CLI-specific setup
   * @returns {Object} Sync result summary
   */
  async sync() {
    const startTime = Date.now();
    const results = {
      cliType: this.cliType,
      cliFolder: this.getCliFolder(),
      synced: [],
      errors: []
    };

    try {
      // 1. Ensure CLI folder exists
      this.ensureCliFolder();
      results.synced.push('cli-folder');

      // 2. Sync skills
      try {
        this.syncSkills();
        results.synced.push('skills');
      } catch (err) {
        results.errors.push({ step: 'skills', error: err.message });
      }

      // 3. Sync rules
      try {
        this.syncRules();
        results.synced.push('rules');
      } catch (err) {
        results.errors.push({ step: 'rules', error: err.message });
      }

      // 4. Sync knowledge files (stack.md, architecture.md, testing.md)
      try {
        const syncedCount = this.syncKnowledgeFiles();
        if (syncedCount > 0) {
          results.synced.push('knowledge-files');
        }
      } catch (err) {
        results.errors.push({ step: 'knowledge-files', error: err.message });
      }

      // 5. Generate rules file
      try {
        this.generateRulesFile();
        results.synced.push('rules-file');
      } catch (err) {
        results.errors.push({ step: 'rules-file', error: err.message });
      }

      // 6. CLI-specific setup
      try {
        const config = this.readConfig();
        await this.setupCliSpecific(config);
        results.synced.push('cli-specific');
      } catch (err) {
        results.errors.push({ step: 'cli-specific', error: err.message });
      }

    } catch (err) {
      results.errors.push({ step: 'general', error: err.message });
    }

    results.duration = Date.now() - startTime;
    results.success = results.errors.length === 0;

    return results;
  }

  // ==================== Utility Methods ====================

  /**
   * Copy a directory recursively
   */
  copyDirRecursive(source, target) {
    if (!fs.existsSync(target)) {
      fs.mkdirSync(target, { recursive: true });
    }

    const items = fs.readdirSync(source);
    for (const item of items) {
      const sourcePath = path.join(source, item);
      const targetPath = path.join(target, item);

      if (fs.statSync(sourcePath).isDirectory()) {
        this.copyDirRecursive(sourcePath, targetPath);
      } else {
        fs.copyFileSync(sourcePath, targetPath);
      }
    }
  }

  /**
   * Log a message (if verbose mode is on)
   */
  log(message) {
    if (this.verbose) {
      console.log(`[${this.cliType}] ${message}`);
    }
  }
}

module.exports = BaseBridge;
