/**
 * Base Bridge Class
 *
 * Abstract base class for CLI bridges. Currently only Claude Code is supported.
 * Generates CLI-specific file structure from the universal .workflow/ config.
 *
 * Architecture:
 *
 * .workflow/                    ← Universal source of truth
 * ├── config.json              ← Contains cli.type setting
 * ├── models/                  ← Model registry
 * ├── skills/                  ← Skills
 * └── templates/               ← Templates for generating CLI files
 *          │
 *          ▼ (bridge generates CLI-specific files)
 * .claude/                     ← Generated by claude-bridge
 */

const fs = require('fs');
const path = require('path');

// Import safeJsonParse from flow-utils to avoid duplicate implementation
let safeJsonParse;
try {
  safeJsonParse = require('../../scripts/flow-utils').safeJsonParse;
} catch {
  // Fallback if flow-utils not available
  safeJsonParse = null;
}

class BaseBridge {
  /**
   * @param {string} cliType - The CLI type identifier (e.g., 'claude-code')
   * @param {Object} options - Configuration options
   * @param {string} options.workflowDir - Path to .workflow directory
   * @param {string} options.projectDir - Path to project root
   */
  constructor(cliType, options = {}) {
    this.cliType = cliType;
    this.workflowDir = options.workflowDir || '.workflow';
    this.projectDir = options.projectDir || process.cwd();
    this.verbose = options.verbose || false;

    // Note: These properties are deprecated in favor of getter methods below.
    // Kept for backwards compatibility with any subclasses that set them directly.
    // New subclasses should override getCliFolder(), getRulesFileName(), etc.
    this.cliFolder = null;
    this.rulesFile = null;
    this.skillsPath = null;
    this.rulesPath = null;
  }

  /**
   * Get the CLI-specific folder name
   * @abstract
   * @returns {string}
   */
  getCliFolder() {
    throw new Error('Subclass must implement getCliFolder()');
  }

  /**
   * Get the rules file name (e.g., CLAUDE.md)
   * @abstract
   * @returns {string}
   */
  getRulesFileName() {
    throw new Error('Subclass must implement getRulesFileName()');
  }

  /**
   * Get the path where skills should be synced
   * @abstract
   * @returns {string}
   */
  getSkillsPath() {
    throw new Error('Subclass must implement getSkillsPath()');
  }

  /**
   * Get the path where rules should be synced
   * @abstract
   * @returns {string}
   */
  getRulesPath() {
    throw new Error('Subclass must implement getRulesPath()');
  }

  /**
   * Generate the main rules/instructions file content
   * @abstract
   * @param {Object} config - The workflow config
   * @returns {string}
   */
  generateRulesContent(config) {
    throw new Error('Subclass must implement generateRulesContent()');
  }

  /**
   * Perform any CLI-specific setup
   * @abstract
   * @param {Object} config - The workflow config
   */
  async setupCliSpecific(config) {
    // Default: no-op. Override in subclasses if needed.
  }

  // ==================== Common Methods ====================

  /**
   * Safe JSON parse that checks for prototype pollution (fallback when flow-utils unavailable)
   *
   * NOTE: This is a fallback implementation. When flow-utils is available,
   * safeJsonParse from flow-utils is used instead (it performs recursive
   * validation of the parsed object). This fallback only does pre-parse
   * string checking which is less comprehensive but better than nothing.
   *
   * @param {string} content - JSON string to parse
   * @returns {Object|null} Parsed object or null if invalid
   */
  safeJsonParseContent(content) {
    if (!content || typeof content !== 'string') {
      return null;
    }

    // Check for prototype pollution attempts
    // These patterns look for dangerous keys that could be used for prototype pollution
    const dangerousPatterns = [
      /__proto__/i,
      /"constructor"\s*:/,
      /"prototype"\s*:/
    ];

    for (const pattern of dangerousPatterns) {
      if (pattern.test(content)) {
        this.log('Warning: Potential prototype pollution detected in JSON');
        return null;
      }
    }

    try {
      const parsed = JSON.parse(content);
      if (parsed === null || typeof parsed !== 'object') {
        return null;
      }

      // Additional check: verify no __proto__ keys in parsed result
      // (JSON.parse could still create them in some edge cases)
      const hasProtoKey = (obj) => {
        if (!obj || typeof obj !== 'object') return false;
        if (Object.prototype.hasOwnProperty.call(obj, '__proto__')) return true;
        for (const value of Object.values(obj)) {
          if (typeof value === 'object' && value !== null && hasProtoKey(value)) {
            return true;
          }
        }
        return false;
      };

      if (hasProtoKey(parsed)) {
        this.log('Warning: __proto__ key detected in parsed JSON');
        return null;
      }

      return parsed;
    } catch (err) {
      if (process.env.DEBUG) {
        this.log(`JSON parse error: ${err.message}`);
      }
      return null;
    }
  }

  /**
   * Read the workflow config
   * @returns {Object}
   */
  readConfig() {
    const configPath = path.join(this.projectDir, this.workflowDir, 'config.json');
    if (!fs.existsSync(configPath)) {
      throw new Error(`Config not found: ${configPath}`);
    }

    // Use flow-utils safeJsonParse if available, otherwise fall back to class method
    let config;
    if (safeJsonParse) {
      config = safeJsonParse(configPath, null);
    } else {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = this.safeJsonParseContent(content);
    }

    if (!config) {
      throw new Error(`Invalid config format: ${configPath}`);
    }
    return config;
  }

  /**
   * Ensure the CLI folder exists
   */
  ensureCliFolder() {
    const cliFolder = path.join(this.projectDir, this.getCliFolder());
    if (!fs.existsSync(cliFolder)) {
      // Use explicit permissions (0o755 = rwxr-xr-x) to avoid relying on umask
      fs.mkdirSync(cliFolder, { recursive: true, mode: 0o755 });
      this.log(`Created ${this.getCliFolder()}/`);
    }
  }

  /**
   * Sync skills from .workflow/skills/ to CLI-specific location
   */
  syncSkills() {
    const sourceSkillsDir = path.join(this.projectDir, this.workflowDir, 'skills');
    const targetSkillsDir = path.join(this.projectDir, this.getSkillsPath());

    if (!fs.existsSync(sourceSkillsDir)) {
      this.log('No skills to sync (no .workflow/skills/ directory)');
      return;
    }

    // Ensure target directory exists with explicit permissions
    if (!fs.existsSync(targetSkillsDir)) {
      fs.mkdirSync(targetSkillsDir, { recursive: true, mode: 0o755 });
    }

    // Copy skills
    const skills = fs.readdirSync(sourceSkillsDir).filter(item => {
      const itemPath = path.join(sourceSkillsDir, item);
      return fs.statSync(itemPath).isDirectory();
    });

    for (const skill of skills) {
      const sourcePath = path.join(sourceSkillsDir, skill);
      const targetPath = path.join(targetSkillsDir, skill);

      this.copyDirRecursive(sourcePath, targetPath);
      this.log(`Synced skill: ${skill}`);
    }

    // Also copy skills-index.json if it exists
    const indexPath = path.join(sourceSkillsDir, 'skills-index.json');
    if (fs.existsSync(indexPath)) {
      fs.copyFileSync(indexPath, path.join(targetSkillsDir, 'skills-index.json'));
      this.log('Synced skills-index.json');
    }
  }

  /**
   * Sync rules from .workflow/state/decisions.md to CLI-specific rules folder
   */
  syncRules() {
    const rulesDir = path.join(this.projectDir, this.getRulesPath());

    // Ensure rules directory exists with explicit permissions
    if (!fs.existsSync(rulesDir)) {
      fs.mkdirSync(rulesDir, { recursive: true, mode: 0o755 });
    }

    // Copy any existing rules from .workflow/rules/ if present
    const sourceRulesDir = path.join(this.projectDir, this.workflowDir, 'rules');
    if (fs.existsSync(sourceRulesDir)) {
      const rules = fs.readdirSync(sourceRulesDir).filter(f => f.endsWith('.md'));
      for (const rule of rules) {
        fs.copyFileSync(
          path.join(sourceRulesDir, rule),
          path.join(rulesDir, rule)
        );
        this.log(`Synced rule: ${rule}`);
      }
    }
  }

  /**
   * Sync knowledge files from .workflow/state/ to CLI-specific docs folder
   * Also updates the knowledge-sync.json state
   */
  syncKnowledgeFiles() {
    const stateDir = path.join(this.projectDir, this.workflowDir, 'state');
    const cliDocsDir = path.join(this.projectDir, this.getCliFolder(), 'docs');

    // Knowledge files to sync
    const knowledgeFiles = ['stack.md', 'architecture.md', 'testing.md'];

    // Ensure CLI docs directory exists with explicit permissions
    if (!fs.existsSync(cliDocsDir)) {
      fs.mkdirSync(cliDocsDir, { recursive: true, mode: 0o755 });
    }

    let syncedCount = 0;
    for (const file of knowledgeFiles) {
      const sourcePath = path.join(stateDir, file);
      const targetPath = path.join(cliDocsDir, file);

      if (fs.existsSync(sourcePath)) {
        fs.copyFileSync(sourcePath, targetPath);
        this.log(`Synced knowledge file: ${file}`);
        syncedCount++;
      }
    }

    // Update knowledge-sync.json after bridge sync
    if (syncedCount > 0) {
      try {
        const knowledgeSync = require('../../scripts/flow-knowledge-sync');
        knowledgeSync.markAsSynced();
        this.log('Updated knowledge-sync.json');
      } catch (err) {
        // flow-knowledge-sync not available
        this.log(`Could not update knowledge-sync state: ${err.message}`);
      }
    }

    return syncedCount;
  }

  /**
   * Generate and write the main rules file (e.g., CLAUDE.md)
   * @param {Object} options - Generation options
   * @param {boolean} options.force - Force overwrite even if locally modified
   */
  generateRulesFile(options = {}) {
    const config = this.readConfig();
    const content = this.generateRulesContent(config);
    const rulesFilePath = path.join(this.projectDir, this.getRulesFileName());

    // Check for local modifications before overwriting
    if (fs.existsSync(rulesFilePath) && !options.force) {
      const existingContent = fs.readFileSync(rulesFilePath, 'utf-8');

      // Check if file was manually modified (missing our generation marker)
      const hasMarker = existingContent.includes('Generated by CLI Bridge');

      if (!hasMarker) {
        // File exists but wasn't generated by us - likely manually created/modified
        this.log(`⚠️  ${this.getRulesFileName()} appears to be manually maintained (no generation marker)`);
        this.log(`   Skipping to preserve local customizations. Use --force to overwrite.`);
        return false;
      }

      // Check if content would actually change
      if (existingContent === content) {
        this.log(`${this.getRulesFileName()} is up to date`);
        return true;
      }

      // File has our marker - safe to overwrite as it's generated content
    }

    fs.writeFileSync(rulesFilePath, content, 'utf-8');
    this.log(`Generated ${this.getRulesFileName()}`);
    return true;
  }

  /**
   * Run full sync: skills, rules, and CLI-specific setup
   * @param {Object} options - Sync options
   * @param {boolean} options.force - Force overwrite of locally modified files
   * @returns {Object} Sync result summary
   */
  async sync(options = {}) {
    const startTime = Date.now();
    const results = {
      cliType: this.cliType,
      cliFolder: this.getCliFolder(),
      synced: [],
      errors: []
    };

    try {
      // 1. Ensure CLI folder exists
      this.ensureCliFolder();
      results.synced.push('cli-folder');

      // 2. Sync skills
      try {
        this.syncSkills();
        results.synced.push('skills');
      } catch (err) {
        results.errors.push({ step: 'skills', error: err.message });
      }

      // 3. Sync rules
      try {
        this.syncRules();
        results.synced.push('rules');
      } catch (err) {
        results.errors.push({ step: 'rules', error: err.message });
      }

      // 4. Sync knowledge files (stack.md, architecture.md, testing.md)
      try {
        const syncedCount = this.syncKnowledgeFiles();
        if (syncedCount > 0) {
          results.synced.push('knowledge-files');
        }
      } catch (err) {
        results.errors.push({ step: 'knowledge-files', error: err.message });
      }

      // 5. Generate rules file (respects local modifications unless --force)
      try {
        const generated = this.generateRulesFile({ force: options.force });
        if (generated) {
          results.synced.push('rules-file');
        } else {
          results.synced.push('rules-file-skipped');
        }
      } catch (err) {
        results.errors.push({ step: 'rules-file', error: err.message });
      }

      // 6. CLI-specific setup
      try {
        const config = this.readConfig();
        await this.setupCliSpecific(config);
        results.synced.push('cli-specific');
      } catch (err) {
        results.errors.push({ step: 'cli-specific', error: err.message });
      }

    } catch (err) {
      results.errors.push({ step: 'general', error: err.message });
    }

    results.duration = Date.now() - startTime;
    results.success = results.errors.length === 0;

    return results;
  }

  // ==================== Template Utility Methods ====================

  /**
   * Get the package root directory (where wogiflow is installed)
   * @returns {string|null} Package root path or null if not found
   */
  getPackageRoot() {
    // Try to find the package by looking up from scripts directory
    const possibleRoots = [
      path.resolve(__dirname, '..', '..'),  // From .workflow/bridges/ -> package root
      path.resolve(__dirname, '..', '..', '..', 'node_modules', 'wogiflow'),  // From project
    ];

    for (const root of possibleRoots) {
      const pkgPath = path.join(root, 'package.json');
      if (fs.existsSync(pkgPath)) {
        try {
          const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
          if (pkg.name === 'wogiflow') {
            return root;
          }
        } catch {
          // Continue to next option
        }
      }
    }
    return null;
  }

  /**
   * Check if a template file is outdated/stub
   * @param {string} templatePath - Path to template file
   * @returns {boolean} True if template appears to be outdated
   */
  isTemplateOutdated(templatePath) {
    if (!fs.existsSync(templatePath)) {
      return true;
    }

    try {
      const content = fs.readFileSync(templatePath, 'utf-8');

      // Check for stub/placeholder markers
      const stubMarkers = [
        'Full implementation pending',
        'stub template',
        'not yet implemented',
        'TODO: implement',
        'placeholder template'
      ];

      for (const marker of stubMarkers) {
        if (content.toLowerCase().includes(marker.toLowerCase())) {
          return true;
        }
      }

      // Check if template is too short (likely incomplete)
      if (content.length < 500) {
        return true;
      }

      return false;
    } catch {
      return true;
    }
  }

  /**
   * Get template path, preferring package template if project template is outdated
   * SECURITY: Validates template name to prevent path traversal attacks
   * @param {string} templateName - Template filename (e.g., 'gemini-md.hbs')
   * @returns {string|null} Path to best available template
   */
  getBestTemplatePath(templateName) {
    // Security: Validate template name to prevent path traversal
    if (!templateName || typeof templateName !== 'string') {
      return null;
    }

    // Block path traversal attempts
    if (templateName.includes('..') || templateName.includes('/') || templateName.includes('\\')) {
      this.log(`Warning: Invalid template name rejected: ${templateName}`);
      return null;
    }

    // Block absolute paths
    if (path.isAbsolute(templateName)) {
      this.log(`Warning: Absolute template path rejected: ${templateName}`);
      return null;
    }

    const projectTemplate = path.join(this.projectDir, this.workflowDir, 'templates', templateName);

    // If project template exists and is not outdated, use it
    if (!this.isTemplateOutdated(projectTemplate)) {
      return projectTemplate;
    }

    // Try to use package template instead
    const packageRoot = this.getPackageRoot();
    if (packageRoot) {
      const packageTemplate = path.join(packageRoot, '.workflow', 'templates', templateName);
      if (fs.existsSync(packageTemplate)) {
        this.log(`Using package template for ${templateName} (project template outdated)`);
        return packageTemplate;
      }
    }

    // Fall back to project template even if outdated
    if (fs.existsSync(projectTemplate)) {
      return projectTemplate;
    }

    return null;
  }

  /**
   * Load a partial template from .workflow/templates/partials/
   * Checks both project and package directories
   * @param {string} partialName - Name of the partial (without .hbs extension)
   * @returns {string} Partial content or empty string if not found
   */
  loadPartial(partialName) {
    // Try project partials first
    const projectPartialPath = path.join(
      this.projectDir,
      this.workflowDir,
      'templates',
      'partials',
      `${partialName}.hbs`
    );

    try {
      if (fs.existsSync(projectPartialPath)) {
        return fs.readFileSync(projectPartialPath, 'utf-8');
      }
    } catch (err) {
      this.log(`Warning: Could not load project partial ${partialName}: ${err.message}`);
    }

    // Try package partials as fallback
    const packageRoot = this.getPackageRoot();
    if (packageRoot) {
      const packagePartialPath = path.join(
        packageRoot,
        '.workflow',
        'templates',
        'partials',
        `${partialName}.hbs`
      );

      try {
        if (fs.existsSync(packagePartialPath)) {
          return fs.readFileSync(packagePartialPath, 'utf-8');
        }
      } catch (err) {
        this.log(`Warning: Could not load package partial ${partialName}: ${err.message}`);
      }
    }

    return '';
  }

  /**
   * Process partial includes in template content
   * Replaces {{> partial-name}} with the partial content
   * @param {string} content - Template content
   * @returns {string} Content with partials included
   */
  processPartials(content) {
    // Match {{> partial-name}} pattern
    const partialRegex = /\{\{>\s*([a-zA-Z0-9_-]+)\s*\}\}/g;

    return content.replace(partialRegex, (match, partialName) => {
      const partialContent = this.loadPartial(partialName);
      if (!partialContent) {
        this.log(`Warning: Partial not found: ${partialName}`);
        return `<!-- Partial not found: ${partialName} -->`;
      }
      return partialContent;
    });
  }

  /**
   * Process {{#if condition}}...{{/if}} blocks in template content
   * Supports nested conditionals by processing innermost first
   * @param {string} content - Template content
   * @param {Object} config - Config object for condition evaluation
   * @returns {string} Content with conditionals evaluated
   */
  processConditionals(content, config) {
    // Match INNERMOST conditionals first - those with no nested {{#if}} in body
    // The negative lookahead (?!{{#if) ensures body contains no nested conditionals
    const innerIfRegex = /\{\{#if\s+([^}]+)\}\}((?:(?!\{\{#if)[\s\S])*?)\{\{\/if\}\}/g;

    let lastContent;
    let iterations = 0;
    const maxIterations = 100; // Safety limit for deeply nested templates

    // Keep processing until no more changes (handles nested conditions)
    do {
      lastContent = content;
      content = content.replace(innerIfRegex, (match, condition, body) => {
        let value;
        if (condition.startsWith('config.')) {
          value = this.getNestedValue(config, condition.replace('config.', ''));
        } else if (condition === 'skills') {
          value = config.skills?.installed?.length > 0;
        } else {
          value = this.getNestedValue(config, condition);
        }
        return value ? body : '';
      });
      iterations++;
    } while (content !== lastContent && iterations < maxIterations);

    if (iterations >= maxIterations) {
      this.log('Warning: Max iterations reached in processConditionals - possible malformed template');
    }

    return content;
  }

  /**
   * Process {{#each array}}...{{/each}} blocks in template content
   * @param {string} content - Template content
   * @param {Object} config - Config object containing arrays
   * @returns {string} Content with each blocks expanded
   */
  processEachBlocks(content, config) {
    const eachRegex = /\{\{#each\s+(\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g;

    return content.replace(eachRegex, (match, arrayName, body) => {
      let array;
      if (arrayName === 'skills') {
        array = config.skills?.installed || [];
      } else {
        array = config[arrayName] || [];
      }

      if (!Array.isArray(array) || array.length === 0) {
        return '';
      }

      // Replace {{this}} in body with each array item
      return array.map(item => body.replace(/\{\{this\}\}/g, String(item))).join('');
    });
  }

  /**
   * Get nested value from config object using dot notation
   * @param {Object} obj - The object to search
   * @param {string} path - Dot-separated path (e.g., 'hooks.rules.taskGating')
   * @returns {*} The value or undefined
   */
  getNestedValue(obj, path) {
    if (!path || typeof path !== 'string') return undefined;

    const parts = path.split('.');
    let current = obj;

    for (const part of parts) {
      if (current === null || current === undefined) return undefined;
      // Security: skip dangerous property names
      if (part === '__proto__' || part === 'constructor' || part === 'prototype') {
        return undefined;
      }
      current = current[part];
    }

    return current;
  }

  // ==================== Utility Methods ====================

  /**
   * Copy a directory recursively
   */
  copyDirRecursive(source, target) {
    if (!fs.existsSync(target)) {
      fs.mkdirSync(target, { recursive: true, mode: 0o755 });
    }

    const items = fs.readdirSync(source);
    for (const item of items) {
      const sourcePath = path.join(source, item);
      const targetPath = path.join(target, item);

      if (fs.statSync(sourcePath).isDirectory()) {
        this.copyDirRecursive(sourcePath, targetPath);
      } else {
        fs.copyFileSync(sourcePath, targetPath);
      }
    }
  }

  /**
   * Log a message (if verbose mode is on)
   */
  log(message) {
    if (this.verbose) {
      console.log(`[${this.cliType}] ${message}`);
    }
  }
}

module.exports = BaseBridge;
