#!/usr/bin/env node

/**
 * Wogi Flow - OpenCode CLI Bridge
 *
 * Generates AGENTS.md, .opencode/opencode.json, and WogiFlow plugin from WogiFlow configuration.
 * Provides HARD ENFORCEMENT via OpenCode's native plugin system - the first non-Claude CLI
 * with full enforcement capability.
 *
 * Key difference from Codex: OpenCode supports native plugins that can BLOCK operations
 * by throwing errors, giving us the same level of control as Claude Code hooks.
 */

const fs = require('fs');
const path = require('path');
const BaseBridge = require('./base-bridge');

// Try to load Handlebars, fall back to inline templates if not available
let Handlebars;
try {
  Handlebars = require('handlebars');
} catch {
  Handlebars = null;
}

// ============================================================
// OpenCode Bridge Class
// ============================================================

class OpenCodeBridge extends BaseBridge {
  constructor(options = {}) {
    super('opencode', options);
  }

  // ==================== Abstract Method Implementations ====================

  getCliFolder() {
    return '.opencode';
  }

  getRulesFileName() {
    return 'AGENTS.md';
  }

  getSkillsPath() {
    return path.join('.opencode', 'skills');
  }

  getRulesPath() {
    return path.join('.opencode', 'rules');
  }

  /**
   * Generate AGENTS.md content
   */
  generateRulesContent(config) {
    const context = this.buildContext(config);

    // Try to use Handlebars template with proper error handling
    if (Handlebars) {
      try {
        const templatePath = path.join(this.projectDir, this.workflowDir, 'templates', 'opencode-agents-md.hbs');
        if (fs.existsSync(templatePath)) {
          const templateSource = fs.readFileSync(templatePath, 'utf-8');
          const template = Handlebars.compile(templateSource);
          return template(context);
        }
      } catch (err) {
        // Template failed - fall through to inline generation
        this.log(`Template generation failed, using fallback: ${err.message}`);
      }
    }

    // Fallback to inline generation
    return this.generateAgentsMdFallback(context);
  }

  /**
   * OpenCode-specific setup: generate opencode.json config and WogiFlow plugin
   */
  async setupCliSpecific(config) {
    // Generate opencode.json
    const configJsonPath = path.join(this.projectDir, this.getCliFolder(), 'opencode.json');
    const configJsonContent = this.generateOpenCodeConfig(config);
    fs.writeFileSync(configJsonPath, configJsonContent);
    this.log('Generated .opencode/opencode.json');

    // Create plugins directory
    const pluginsDir = path.join(this.projectDir, this.getCliFolder(), 'plugins');
    if (!fs.existsSync(pluginsDir)) {
      fs.mkdirSync(pluginsDir, { recursive: true, mode: 0o755 });
    }

    // Generate WogiFlow plugin
    const pluginPath = path.join(pluginsDir, 'wogiflow.js');
    const pluginContent = this.generateWogiFlowPlugin(config);
    fs.writeFileSync(pluginPath, pluginContent);
    this.log('Generated .opencode/plugins/wogiflow.js');

    // Convert Claude skills to OpenCode format
    this.convertAndSyncSkills();
  }

  // ==================== OpenCode-Specific Methods ====================

  /**
   * Build template context
   */
  buildContext(config) {
    // Load decisions.md for coding rules
    const decisionsPath = path.join(this.projectDir, this.workflowDir, 'state', 'decisions.md');
    let decisions = '';
    try {
      decisions = fs.readFileSync(decisionsPath, 'utf-8');
    } catch (err) {
      // File may not exist or be unreadable - continue with empty decisions
      if (err.code !== 'ENOENT') {
        this.log(`Failed to read decisions.md: ${err.message}`);
      }
    }

    // Get installed skills
    const skills = config.skills?.installed || [];

    return {
      projectName: path.basename(this.projectDir),
      projectRoot: this.projectDir,
      timestamp: new Date().toISOString(),
      config,
      decisions,
      skills,
      enforcement: config.enforcement || {},
      research: config.research || {},
      qualityGates: config.qualityGates || {},
      commits: config.commits || {},
      // OpenCode-specific: indicate plugin enforcement is available
      hasPluginEnforcement: true
    };
  }

  /**
   * Fallback AGENTS.md generation (no Handlebars)
   */
  generateAgentsMdFallback(context) {
    const lines = [];

    lines.push('# WogiFlow Project Instructions');
    lines.push('');
    lines.push(`> Generated by WogiFlow OpenCode Bridge - ${context.timestamp}`);
    lines.push('');
    lines.push('You are an AI development assistant using the WogiFlow methodology. This is a self-improving workflow that learns from feedback and adapts to preferences.');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Enforcement Notice');
    lines.push('');
    lines.push('**This project uses WogiFlow with HARD ENFORCEMENT via OpenCode plugins.**');
    lines.push('');
    lines.push('The WogiFlow plugin will:');
    lines.push('- Block file edits without an active task');
    lines.push('- Inject context at session start');
    lines.push('- Run validation after file changes');
    lines.push('- Trigger research protocol for capability questions');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Core Principles');
    lines.push('');
    lines.push('1. **State files are memory** - Read `.workflow/state/` first');
    lines.push('2. **Config drives behavior** - Follow `.workflow/config.json` rules');
    lines.push('3. **Log every change** - Append to `request-log.md`');
    lines.push('4. **Reuse components** - Check `app-map.md` before creating');
    lines.push('5. **Learn from feedback** - Update instructions when corrected');
    lines.push('');

    // Task Gating
    if (context.enforcement?.strictMode) {
      lines.push('## Task Gating (MANDATORY - ENFORCED BY PLUGIN)');
      lines.push('');
      lines.push('**The WogiFlow plugin will BLOCK edits without an active task.**');
      lines.push('');
      lines.push('Before ANY implementation work:');
      lines.push('1. Check `.workflow/state/ready.json` for existing tasks');
      lines.push('2. If task exists → Use `/wogi-start TASK-XXX`');
      lines.push('3. If no task → Create with `/wogi-story "title"` first');
      lines.push('');
    }

    // Research Protocol
    if (context.research?.enabled) {
      lines.push('## Research Protocol (ENFORCED BY PLUGIN)');
      lines.push('');
      lines.push('For capability/feasibility/existence questions, **BEFORE answering:**');
      lines.push('');
      lines.push('1. **Scope Mapping** - Identify relevant files and sources');
      lines.push('2. **Local Evidence** - Read ALL relevant files (don\'t skim)');
      lines.push('3. **External Verification** - Web search for current docs');
      lines.push('4. **Assumption Check** - List and verify each assumption');
      lines.push('5. **Synthesis** - Answer with citations and confidence level');
      lines.push('');
      lines.push('**FORBIDDEN:**');
      lines.push('- Claiming "X doesn\'t exist" without exhaustive search');
      lines.push('- Using training data for external tool capabilities');
      lines.push('- Skipping verification steps');
      lines.push('');
    }

    // Essential Commands
    lines.push('## Essential Commands');
    lines.push('');
    lines.push('| Command | Purpose |');
    lines.push('|---------|---------|');
    lines.push('| `/wogi-ready` | Show available tasks |');
    lines.push('| `/wogi-start TASK-X` | Start task with context |');
    lines.push('| `/wogi-story "title"` | Create story with AC |');
    lines.push('| `/wogi-status` | Project overview |');
    lines.push('| `/wogi-research "q"` | Research before answering |');
    lines.push('');
    lines.push('See `.claude/docs/commands.md` for complete reference.');
    lines.push('');

    // Request Logging
    lines.push('## Request Logging');
    lines.push('');
    lines.push('After EVERY request that changes files:');
    lines.push('');
    lines.push('```markdown');
    lines.push('### R-[XXX] | [YYYY-MM-DD HH:MM]');
    lines.push('**Type**: new | fix | change | refactor');
    lines.push('**Tags**: #screen:[name] #component:[name]');
    lines.push('**Request**: "[what user asked]"');
    lines.push('**Result**: [what was done]');
    lines.push('**Files**: [files changed]');
    lines.push('```');
    lines.push('');

    // Component Reuse
    lines.push('## Component Reuse');
    lines.push('');
    lines.push('**Before creating ANY component:**');
    lines.push('1. Check `app-map.md`');
    lines.push('2. Search codebase for existing');
    lines.push('3. Priority: Use existing → Add variant → Extend → Create new (last resort)');
    lines.push('');

    // Auto-Validation
    lines.push('## Auto-Validation (ENFORCED BY PLUGIN)');
    lines.push('');
    lines.push('The WogiFlow plugin automatically runs validation after file edits.');
    lines.push('Results are injected as system messages.');
    lines.push('');
    lines.push('Manual validation:');
    lines.push('```bash');
    lines.push('npx tsc --noEmit 2>&1 | head -20');
    lines.push('npx eslint [file] --fix');
    lines.push('```');
    lines.push('');

    // File Locations
    lines.push('## File Locations');
    lines.push('');
    lines.push('| What | Where |');
    lines.push('|------|-------|');
    lines.push('| Config | `.workflow/config.json` |');
    lines.push('| Tasks | `.workflow/state/ready.json` |');
    lines.push('| Logs | `.workflow/state/request-log.md` |');
    lines.push('| Components | `.workflow/state/app-map.md` |');
    lines.push('| Rules | `.workflow/state/decisions.md` |');
    lines.push('| Progress | `.workflow/state/progress.md` |');
    lines.push('');

    // Skills
    if (context.skills && context.skills.length > 0) {
      lines.push('## Installed Skills');
      lines.push('');
      for (const skill of context.skills) {
        lines.push(`- ${skill}`);
      }
      lines.push('');
      lines.push('Check `.opencode/skills/[name]/SKILL.md` for skill-specific guidance.');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push('**Note:** This is OpenCode CLI configuration with WogiFlow hard enforcement via native plugins.');
    lines.push('');
    lines.push('*Edit `.workflow/templates/opencode-agents-md.hbs` to customize. Run `flow bridge sync opencode` to regenerate.*');

    return lines.join('\n');
  }

  /**
   * Generate .opencode/opencode.json config content
   */
  generateOpenCodeConfig(config) {
    const context = this.buildContext(config);

    // Try to use Handlebars template with proper error handling
    if (Handlebars) {
      try {
        const templatePath = path.join(this.projectDir, this.workflowDir, 'templates', 'opencode-config.hbs');
        if (fs.existsSync(templatePath)) {
          const templateSource = fs.readFileSync(templatePath, 'utf-8');
          const template = Handlebars.compile(templateSource);
          return template(context);
        }
      } catch (err) {
        // Template failed - fall through to inline generation
        this.log(`Config template failed, using fallback: ${err.message}`);
      }
    }

    // Fallback to inline JSON generation
    return this.generateOpenCodeConfigFallback(context);
  }

  /**
   * Fallback opencode.json generation
   */
  generateOpenCodeConfigFallback(context) {
    const config = {
      $schema: 'https://opencode.ai/schema/config.json',
      version: '1.0',

      // Context files to load
      context: {
        files: [
          'AGENTS.md',
          '.workflow/state/decisions.md'
        ]
      },

      // WogiFlow plugin configuration
      plugins: {
        wogiflow: {
          enabled: true,
          path: './plugins/wogiflow.js'
        }
      },

      // MCP servers (if configured)
      mcp: {
        servers: {}
      },

      // Tool permissions
      tools: {
        sandbox: false,
        allowed: ['file_write', 'file_read', 'shell_execute']
      }
    };

    return JSON.stringify(config, null, 2);
  }

  /**
   * Generate the WogiFlow plugin for OpenCode
   */
  generateWogiFlowPlugin(config) {
    const projectRoot = this.projectDir;
    const enforcement = config.enforcement || {};
    const research = config.research || {};
    const validation = config.qualityGates || {};

    return `#!/usr/bin/env node

/**
 * WogiFlow Plugin for OpenCode CLI
 *
 * Provides HARD ENFORCEMENT of workflow rules:
 * - Task gating (must start task before editing)
 * - Component reuse checking
 * - Post-edit validation
 * - Research protocol enforcement
 *
 * Generated by WogiFlow OpenCode Bridge
 * Timestamp: ${new Date().toISOString()}
 */

const path = require('path');

// Project root for loading core modules
// SECURITY: Using JSON.stringify to safely escape special characters
const PROJECT_ROOT = ${JSON.stringify(projectRoot)};

// Lazy-load core modules to avoid startup cost
let coreModules = null;

function loadCoreModules() {
  if (coreModules) return coreModules;

  try {
    const scriptsPath = path.join(PROJECT_ROOT, 'scripts', 'hooks', 'core');
    coreModules = {
      constants: require(path.join(scriptsPath, 'constants')),
      taskGate: require(path.join(scriptsPath, 'task-gate')),
      scopeGate: require(path.join(scriptsPath, 'scope-gate')),
      validation: require(path.join(scriptsPath, 'validation')),
      sessionContext: require(path.join(scriptsPath, 'session-context')),
      componentCheck: require(path.join(scriptsPath, 'component-check'))
    };

    // Try to load research gate (may not exist)
    try {
      coreModules.researchGate = require(path.join(scriptsPath, 'research-gate'));
    } catch {
      coreModules.researchGate = null;
    }
  } catch (err) {
    console.error('[WogiFlow Plugin] Failed to load core modules:', err.message);
    coreModules = {};
  }

  return coreModules;
}

// ============================================================
// Configuration (from bridge sync)
// ============================================================

const ENFORCEMENT_CONFIG = {
  strictMode: ${enforcement.strictMode === true},
  taskGating: ${enforcement.taskGating?.enabled !== false},
  scopeGating: ${enforcement.scopeGating?.enabled !== false},
  componentCheck: ${enforcement.componentCheck?.enabled !== false},
  validation: ${validation.enabled !== false},
  research: ${research.enabled === true}
};

// ============================================================
// Plugin Export
// ============================================================

module.exports = {
  name: 'wogiflow',
  version: '1.0.0',

  hooks: {
    /**
     * Session start - inject WogiFlow context
     */
    'session.start': async (ctx) => {
      const core = loadCoreModules();
      if (!core.sessionContext) {
        return {};
      }

      try {
        const result = core.sessionContext.gatherSessionContext({
          includeSuspended: true,
          includeDecisions: true,
          includeActivity: true
        });

        if (result.enabled && result.context) {
          const contextText = core.sessionContext.formatContextForInjection(result);
          return { additionalContext: contextText };
        }
      } catch (err) {
        console.error('[WogiFlow Plugin] session.start error:', err.message);
      }

      return {};
    },

    /**
     * Before tool execution - task gating + component check
     * THROWS to block operations
     */
    'tool.execute.before': async (ctx) => {
      const { toolName, toolInput } = ctx;

      const core = loadCoreModules();

      // Only gate file write operations (use shared constants)
      const writeTools = core.constants?.WRITE_TOOLS || ['file_write', 'edit_file', 'replace', 'Edit', 'Write'];
      if (!writeTools.includes(toolName)) {
        return {};
      }

      // SECURITY: Validate and extract file path
      const filePath = toolInput?.path || toolInput?.file_path;
      if (!filePath || typeof filePath !== 'string' || filePath.length > 5000) {
        return {};
      }

      // core already loaded above - no redeclaration needed

      // Task + scope gating check
      if (ENFORCEMENT_CONFIG.taskGating && core.scopeGate) {
        try {
          const result = core.scopeGate.checkScopeGate({
            filePath,
            operation: 'write'
          });

          if (result.blocked) {
            // HARD ENFORCEMENT: throw to block
            throw new Error(result.message || 'Task not started. Run /wogi-start first.');
          }

          if (result.warning) {
            return { systemMessage: result.message };
          }
        } catch (err) {
          if (err.message.includes('/wogi-start') || err.message.includes('blocked')) {
            throw err; // Re-throw blocking errors
          }
          console.error('[WogiFlow Plugin] task gate error:', err.message);
        }
      }

      // Component reuse check (for new files)
      if (ENFORCEMENT_CONFIG.componentCheck && core.componentCheck && toolName === 'Write') {
        try {
          const result = core.componentCheck.checkComponentReuse({
            filePath,
            content: toolInput?.content
          });

          if (result.blocked) {
            throw new Error(result.message || 'Component reuse check failed.');
          }

          if (result.warning) {
            return { systemMessage: result.message };
          }
        } catch (err) {
          if (err.message.includes('reuse') || err.message.includes('blocked')) {
            throw err;
          }
          console.error('[WogiFlow Plugin] component check error:', err.message);
        }
      }

      return {};
    },

    /**
     * After tool execution - run validation
     */
    'tool.execute.after': async (ctx) => {
      const { toolName, toolInput, toolResponse } = ctx;

      const core = loadCoreModules();

      // Only validate file write operations (use shared constants)
      const writeTools = core.constants?.WRITE_TOOLS || ['file_write', 'edit_file', 'replace', 'Edit', 'Write'];
      if (!writeTools.includes(toolName)) {
        return {};
      }

      if (!ENFORCEMENT_CONFIG.validation) {
        return {};
      }

      // SECURITY: Validate file path
      const filePath = toolInput?.path || toolInput?.file_path;
      if (!filePath || typeof filePath !== 'string') {
        return {};
      }

      if (!core.validation) {
        return {};
      }

      try {
        const result = await core.validation.runValidation({ filePath });

        if (result.summary) {
          return {
            systemMessage: result.summary,
            severity: result.blocked ? 'error' : (result.passed ? 'info' : 'warning')
          };
        }
      } catch (err) {
        console.error('[WogiFlow Plugin] validation error:', err.message);
      }

      return {};
    },

    /**
     * Prompt append - research gate
     */
    'tui.prompt.append': async (ctx) => {
      const { prompt } = ctx;

      if (!ENFORCEMENT_CONFIG.research || !prompt) {
        return {};
      }

      const core = loadCoreModules();
      if (!core.researchGate) {
        return {};
      }

      try {
        const result = core.researchGate.checkResearchRequirement({ prompt });

        if (result.injectProtocol && result.protocolSteps) {
          return { additionalContext: result.protocolSteps };
        }

        if (result.suggestedCommand) {
          return {
            additionalContext: \`Research recommended: \${result.suggestedCommand}\`
          };
        }
      } catch (err) {
        console.error('[WogiFlow Plugin] research gate error:', err.message);
      }

      return {};
    }
  }
};
`;
  }

  /**
   * Convert Claude skills to OpenCode SKILL.md format
   */
  convertAndSyncSkills() {
    const claudeSkillsDir = path.join(this.projectDir, '.claude', 'skills');
    const opencodeSkillsDir = path.join(this.projectDir, this.getSkillsPath());

    if (!fs.existsSync(claudeSkillsDir)) {
      this.log('No Claude skills to convert');
      return;
    }

    // Ensure OpenCode skills directory exists with explicit permissions
    if (!fs.existsSync(opencodeSkillsDir)) {
      fs.mkdirSync(opencodeSkillsDir, { recursive: true, mode: 0o755 });
    }

    let skillDirs;
    try {
      skillDirs = fs.readdirSync(claudeSkillsDir, { withFileTypes: true })
        .filter(d => d.isDirectory())
        .map(d => d.name);
    } catch (err) {
      this.log(`Failed to read skills directory: ${err.message}`);
      return;
    }

    let converted = 0;
    let skipped = 0;

    for (const skillName of skillDirs) {
      try {
        // SECURITY: Validate skillName to prevent path traversal
        const safeSkillName = path.basename(skillName);
        if (safeSkillName !== skillName) {
          this.log(`Skipping suspicious skill name: ${skillName}`);
          skipped++;
          continue;
        }

        // Additional validation: only alphanumeric, dash, underscore
        if (!/^[a-zA-Z0-9_-]+$/.test(safeSkillName)) {
          this.log(`Skipping skill with invalid characters: ${skillName}`);
          skipped++;
          continue;
        }

        // SECURITY: Verify resolved paths stay within expected directories
        const resolvedClaudeDir = path.resolve(claudeSkillsDir);
        const resolvedSkillPath = path.resolve(claudeSkillsDir, safeSkillName);
        if (!resolvedSkillPath.startsWith(resolvedClaudeDir + path.sep)) {
          this.log(`Path traversal attempt blocked: ${skillName}`);
          skipped++;
          continue;
        }

        const claudeSkillMd = path.join(claudeSkillsDir, safeSkillName, 'skill.md');

        if (fs.existsSync(claudeSkillMd)) {
          const content = fs.readFileSync(claudeSkillMd, 'utf-8');
          const opencodeContent = this.convertSkillToOpenCode(safeSkillName, content);

          // Create OpenCode skill directory with explicit permissions
          const opencodeSkillDir = path.join(opencodeSkillsDir, safeSkillName);
          if (!fs.existsSync(opencodeSkillDir)) {
            fs.mkdirSync(opencodeSkillDir, { recursive: true, mode: 0o755 });
          }

          // Write SKILL.md (OpenCode format - same as Codex)
          fs.writeFileSync(path.join(opencodeSkillDir, 'SKILL.md'), opencodeContent);
          this.log(`Converted skill: ${safeSkillName}`);
          converted++;
        }
      } catch (err) {
        this.log(`Failed to convert skill ${skillName}: ${err.message}`);
        skipped++;
      }
    }

    if (converted > 0 || skipped > 0) {
      this.log(`Skill sync complete: ${converted} converted, ${skipped} skipped`);
    }
  }

  /**
   * Convert a Claude skill.md to OpenCode SKILL.md format
   */
  convertSkillToOpenCode(skillName, claudeContent) {
    const lines = [];

    // Parse Claude frontmatter if present
    let description = `WogiFlow ${skillName} skill`;
    let body = claudeContent;

    const frontmatterMatch = claudeContent.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (frontmatterMatch) {
      const frontmatter = frontmatterMatch[1];
      body = frontmatterMatch[2].trim();

      const descMatch = frontmatter.match(/description:\s*["']?([^"'\n]+)["']?/);
      if (descMatch) {
        description = descMatch[1];
      }
    }

    // Generate OpenCode SKILL.md format (same as Codex)
    // Use YAML escaping for values that may contain special characters
    const escapeYaml = (v) => {
      if (!v || typeof v !== 'string') return '""';
      if (/[:\n"'{}[\],&#@!|>*?`\r\t]/.test(v) || v.trim() !== v) {
        return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
      }
      return v;
    };

    lines.push('---');
    lines.push(`name: ${escapeYaml(skillName)}`);
    lines.push(`description: ${escapeYaml(description)}`);
    lines.push('metadata:');
    lines.push(`  short-description: ${escapeYaml(description.slice(0, 50))}`);
    lines.push(`  source: wogi-flow`);
    lines.push(`  enforcement: hard`);
    lines.push('---');
    lines.push('');
    lines.push(body);

    return lines.join('\n');
  }
}

// ============================================================
// Module Exports
// ============================================================

module.exports = OpenCodeBridge;

// CLI interface if run directly
if (require.main === module) {
  const args = process.argv.slice(2);
  const command = args[0];

  const bridge = new OpenCodeBridge({ verbose: true });

  switch (command) {
    case 'sync':
      bridge.sync().then(results => {
        console.log('');
        console.log('OpenCode Bridge Sync Results:');
        console.log(`  Success: ${results.success}`);
        console.log(`  Duration: ${results.duration}ms`);
        console.log(`  Synced: ${results.synced.join(', ')}`);
        if (results.errors.length > 0) {
          console.log(`  Errors: ${results.errors.map(e => e.error).join(', ')}`);
        }
      });
      break;

    case 'status':
      const agentsMdExists = fs.existsSync(path.join(process.cwd(), 'AGENTS.md'));
      const configExists = fs.existsSync(path.join(process.cwd(), '.opencode', 'opencode.json'));
      const pluginExists = fs.existsSync(path.join(process.cwd(), '.opencode', 'plugins', 'wogiflow.js'));

      console.log('OpenCode Bridge Status:');
      console.log(`  AGENTS.md: ${agentsMdExists ? '✓ exists' : '✗ missing'}`);
      console.log(`  .opencode/opencode.json: ${configExists ? '✓ exists' : '✗ missing'}`);
      console.log(`  .opencode/plugins/wogiflow.js: ${pluginExists ? '✓ exists' : '✗ missing'}`);
      break;

    default:
      console.log('WogiFlow OpenCode Bridge');
      console.log('');
      console.log('Commands:');
      console.log('  sync     Sync WogiFlow config to OpenCode format');
      console.log('  status   Check current OpenCode configuration');
      console.log('');
      console.log('Usage:');
      console.log('  node .workflow/bridges/opencode-bridge.js sync');
  }
}
